
services:
  postgres:
    image: postgres:16-alpine 
    container_name: itssayzy_db
    restart: always 
    environment:
      POSTGRES_USER: itssayzy
      POSTGRES_PASSWORD: whittydev2 
      POSTGRES_DB: itssayzy
    ports:
      - "5432:5432" #
    volumes:
      - pg_data:/var/lib/postgresql/data 

volumes:
  pg_data:
